name: Captura escrito CSJ con Playwright

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  run-playwright:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install

      - name: Run Python script
        run: python captura_i2p_playwright.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: escrito-captura
          path: escrito_csj_*.html
