name: Captura escrito CSJ

on:
  schedule:
    - cron: '0 12 * * *'  # Ejecuta todos los días a las 12:00 UTC
  workflow_dispatch:       # Permite ejecución manual

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Install Chrome and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable jq unzip

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          echo "Chrome version: $CHROME_VERSION"
          VERSION_MAJOR_MINOR=$(echo $CHROME_VERSION | cut -d. -f1-2)
          CHROMEDRIVER_VERSION=$(curl -sS https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | \
            jq -r --arg ver "$CHROME_VERSION" '.channels.chromium.versions[] | select(.version | startswith($ver)) | .downloads.chromedriver[0].version' | head -n1)
          if [ -z "$CHROMEDRIVER_VERSION" ]; then
            CHROMEDRIVER_VERSION=$(curl -sS https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | \
              jq -r --arg ver "$VERSION_MAJOR_MINOR" '.channels.chromium.versions[] | select(.version | startswith($ver)) | .downloads.chromedriver[0].version' | head -n1)
          fi
          echo "ChromeDriver version: $CHROMEDRIVER_VERSION"
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run Python script
        run: python captura_i2p.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: escrito-captura
          path: escrito_csj_*.html
